### ISSUE TITLE
Research MyFitnessPal API

### ISSUE THREAD

**Issue by elitetrainingpro** [elitetrainingpro/elitetrainingpro.com#10]
- [ ] Check to see if this will give us what we want.

- [ ] We need to get approved by MyFitnessPal to use it. If it gives us what we want then start the approval process.

Here is the [link](http://www.myfitnesspal.com/api) to MyFitnessPal API Approval.
[This](https://github.com/coddingtonbear/python-myfitnesspa) also might help us.

**Comment by wvmon** [comment]
We will no longer be using the MyFitnessPal API for this project instead we are going to stick with Fitbit API.
