### ISSUE TITLE
Set up hosting site.

### ISSUE THREAD

**Issue by elitetrainingpro** [elitetrainingpro/elitetrainingpro.com#3]
Using the following domain name: elitetrainingpro.org

Step 1:
Call Google and have them switch to JustHost Nameservers
Ns1.justhost.com
Ns2.justhost.com
Could take 1 to 2 days to transfer

Step 2:
After a day or 2 then do:
Assign domain to justhost account.
elitetrainingpro.org as an addon domain.
Lastly, push Production code to server and test the site to see if it is working.

**Comment by hjcoder18** [comment]
Step 1:
Call Google and have them switch to JustHost Nameservers
Ns1.justhost.com
Ns2.justhost.com
Could take 1 to 2 days to transfer

Step 2:
After a day or 2 then do:
Assign domain to justhost account.
elitetrainingpro.org as an addon domain.

**Comment by elitetrainingpro** [comment]
elitetrainingpro.org
