### ISSUE TITLE
Fix the header and footer

### ISSUE THREAD

**Issue by hjcoder18** [elitetrainingpro/elitetrainingpro.com#30]
- Footer is not going all the way across.
- Mobile responsiveness needs to be fixed for the footer (it is not staying at the bottom of the page).

**Comment by wvmon** [comment]
Footer cannot be in a fixed position all the time. Meaning when you scroll all the way down then you see the footer.

**Comment by elitetrainingpro** [comment]
@jaortiz9 will you fix this issue that William found.
